server:
  port: 12306
  servlet:
    encoding:
      force: true
      force-request: true
      force-response: true
spring: 
  profiles: 
    active: dev,config
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non-empty
  mvc: 
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
        
# 大部分配置只在单数据源有效
mybatis:
  # mapper.xml文件
  mapper-locations: classpath:mappers/*.xml
  # 全局配置文件,该全局配置文件中的属性可以直接在application中配置
  configuration:
    # 数据库下划线转驼峰,true为转,false不变
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    local-cache-scope: session
    
# 分页插件
pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  row-bounds-with-count: false
  page-size-zero: false
  reasonable: false
  support-methods-arguments: false
  auto-runtime-dialect: false
    
logging: 
  level: 
    com.wy.mapper: debug